# Generated by Django 3.1.7 on 2021-03-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admindbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutename', models.CharField(max_length=50)),
                ('instituteid', models.IntegerField()),
                ('photo', models.ImageField(upload_to='pics')),
                ('Mail', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Staffdbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('staffid', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Department', models.CharField(max_length=15)),
                ('Mail', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Studentdbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('registernumber', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('dob', models.IntegerField()),
                ('department', models.CharField(max_length=25)),
                ('Staffname', models.CharField(max_length=100)),
                ('Mail', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
    ]
