# Generated by Django 3.1.7 on 2021-03-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Staffname', models.CharField(max_length=20)),
                ('Status', models.BooleanField()),
            ],
        ),
    ]
