# Generated by Django 3.1.7 on 2021-03-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_attendancedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedetails',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
