# Generated by Django 3.1.7 on 2021-03-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210313_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdbs',
            name='Mail',
            field=models.CharField(max_length=32),
        ),
    ]
