# Generated by Django 3.1.7 on 2021-04-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210316_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdbs',
            name='dob',
            field=models.DateField(),
        ),
    ]
